//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPCAFContrib.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPCAFContrib.Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(document).ready(function () {
        ///        $(&quot;td.ms-vb2:contains(&apos;01.01.1900&apos;)&quot;).text(&quot;&quot;);
        ///    });.
        /// </summary>
        internal static string doc_ready {
            get {
                return ResourceManager.GetString("doc_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.prototype.trim = function() {
        ///    return this.replace(/^\s\s*/, &apos;&apos;).replace(/\s\s*$/, &apos;&apos;);
        ///}
        ///
        ///$.urlParam = function (name) {
        ///    var results = new RegExp(&apos;[\\?&amp;]&apos; + name + &apos;=([^&amp;#]*)&apos;).exec(top.window.location.href);
        ///    return (results !== null) ? results[1] : 0;
        ///}
        ///
        ///// Returns the version of Internet Explorer or a -1
        ///// (indicating the use of another browser).
        ///function GetInternetExplorerVersion()
        ///{
        ///    var rv = -1; // Return value assumes failure.
        ///    if (navigator.appName == &apos;Microso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string site_js {
            get {
                return ResourceManager.GetString("site_js", resourceCulture);
            }
        }
    }
}
