//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubPoint2.DocsImport.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class M2Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M2Pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubPoint2.DocsImport.Resources.M2Pages", typeof(M2Pages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;section class=&quot;wrapper wrapper-grey1&quot;&gt;
        ///&lt;p&gt;
        ///	&lt;!-- start: WORKS CONTAINER --&gt;
        ///&lt;/p&gt;
        ///&lt;div class=&quot;container&quot;&gt;
        ///	&lt;div class=&quot;row&quot;&gt;
        ///		&lt;div style=&quot;text-align:center&quot; class=&quot;col-md-8 center text-center&quot;&gt;
        ///			&lt;img src=&apos;http://docs.subpointsolutions.com/wp-content/uploads/2015/03/sp-working1.png&apos;/&gt;
        ///		&lt;/div&gt;
        ///		&lt;div style=&quot;text-align:center&quot; class=&quot;col-md-8 center text-center&quot;&gt;
        ///			&lt;h2&gt;Sorry, the content is being written. &lt;br/&gt;
        ///			Stop by later or give us a shot at Yammer.&lt;/h2&gt;
        ///			&lt;div class=&quot;col-sm-6&quot;&gt;
        ///				&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentBeingWritten {
            get {
                return ResourceManager.GetString("ContentBeingWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using SPMeta2.Docs.ProvisionSamples.Base;
        ///using SPMeta2.Docs.ProvisionSamples.Definitions;
        ///using SPMeta2.Syntax.Default;
        ///
        ///namespace SPMeta2.Docs.ProvisionSamples.Provision.Definitions
        ///{
        ///    [TestClass]
        ///    public class XXXTests : ProvisionTestBase
        ///    {
        ///        #region methods
        ///
        ///        [TestMethod]
        ///        [TestCategory(&quot;Docs.XXX&quot;)]
        ///        public void CanDeploySimpleXXX()
        ///        {
        ///            var model = SPMeta2Model.NewSiteModel(site =&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSTemplate {
            get {
                return ResourceManager.GetString("CSTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- M2-TODO --&gt;
        ///&lt;properties
        ///	  pageTitle=&quot;[PAGE_TITLE]&quot;
        ///    pageName=&quot;[PAGE_NAME]&quot;
        ///    parentPageId=&quot;3981&quot;
        ////&gt;
        ///
        ///###Provision scenario
        ///SCENARIO
        ///
        ///###Scope
        ///SCOPE
        ///
        ///###Implementation
        ///IMPLEMENTATION
        ///
        ///###Samples
        ///A SAMPLE 1
        ///[TEST.TestFunctionName1]
        ///
        ///A SAMPLE 2
        ///[TEST.TestFunctionName2]
        ///
        ///###Links
        ///- [link 1](http://example.com)
        ///- [link 2](http://example.com).
        /// </summary>
        internal static string MDTemplate {
            get {
                return ResourceManager.GetString("MDTemplate", resourceCulture);
            }
        }
    }
}
