//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubPoint2.DocsImport.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MarkdownPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarkdownPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubPoint2.DocsImport.Resources.MarkdownPages", typeof(MarkdownPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## SPMeta2 is now part of &lt;a href=&quot;http://subpointsolutions.com&quot;&gt;SubPoint Solutions&lt;/a&gt;
        ///
        ///&lt;a href=&quot;http://subpointsolutions.com&quot;&gt;SubPoint Solutions&lt;/a&gt; is an inovative company that helps SharePoint professionals and consultancy companies be efficient. 
        ///
        ///We look after &lt;a href=&quot;http://subpointsolutions.com/spmeta2/about&quot;&gt;SPMeta2 library&lt;/a&gt;, &lt;a href=&quot;http://subpointsolutions.com/spcafcontrib/about&quot;&gt;SPCAFContrib&lt;/a&gt; and a few more projects aim to provide a powerful foundation and experience for SharePoint p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutSPMeta2 {
            get {
                return ResourceManager.GetString("AboutSPMeta2", resourceCulture);
            }
        }
    }
}
