//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubPoint2.DocsImport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlTmplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlTmplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubPoint2.DocsImport.HtmlTmplates", typeof(HtmlTmplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;padding: 10px;border:1px #dedede solid;&quot;&gt;
        ///
        ///    &lt;table class=&quot;docs-feedback-cnt&quot; style=&apos;width:100%&apos;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td style=&apos;width:40px&apos;&gt;
        ///                    &lt;i class=&quot;fa fa-file-text-o&quot; style=&quot;font-size: 4em;&quot;&gt;
        ///                    &lt;/i&gt;
        ///                &lt;/td&gt;
        ///                &lt;td style=&quot;padding-left: 20px;width:255px&quot;&gt;
        ///                    &lt;div&gt;
        ///                        &lt;h4&gt;Help us improve this article.&lt;/h4&gt;
        ///                    &lt;/div&gt;
        ///                &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocImproveAres {
            get {
                return ResourceManager.GetString("DocImproveAres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li class=&quot;[ITEM-CLASS]&quot;&gt;
        ///    &lt;div class=&quot;timeline-badge info&quot;&gt;[DATE]&lt;/div&gt;
        ///    &lt;div class=&quot;timeline-panel&quot;&gt;
        ///        &lt;div class=&quot;timeline-heading&quot;&gt;
        ///            &lt;h4 class=&quot;timeline-title&quot;&gt;[TITLE]&lt;/h4&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;timeline-body&quot;&gt;
        ///            [CONTENT]
        ///            &lt;hr&gt;
        ///            &lt;div class=&quot;btn-group&quot;&gt;
        ///                [BUTTONS]
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/li&gt;.
        /// </summary>
        internal static string MainReleaseTimelineItem {
            get {
                return ResourceManager.GetString("MainReleaseTimelineItem", resourceCulture);
            }
        }
    }
}
