using System.Collections.Generic;

namespace ReSharePoint.Entities
{
    /// <summary>
    /// List of the SP 2013 default managaed properties
    /// http://technet.microsoft.com/en-us/library/jj219630.aspx
    /// </summary>
    public static class SP2013ManagedProperties
    {
        #region classes

        public class ManagedProperty
        {
            public string Name { get; set; }
            public string Type { get; set; }
            public bool MultiValued { get; set; }
            public bool Queryable { get; set; }
            public bool Searchable { get; set; }
            public bool Retrievable { get; set; }
            public bool Refinable { get; set; }
            public bool Sortable { get; set; }
        }

        #endregion

        #region properties

        public static readonly List<ManagedProperty> DefaultProperties = new List<ManagedProperty> 
        {
            new ManagedProperty {  Name =  "AboutMe" },
            new ManagedProperty {  Name =  "Account" },
            new ManagedProperty {  Name =  "AccountName" },
            new ManagedProperty {  Name =  "acronym" },
            new ManagedProperty {  Name =  "acronymaggre" },
            new ManagedProperty {  Name =  "acronymexpansion" },
            new ManagedProperty {  Name =  "acronymexpansionaggre" },
            new ManagedProperty {  Name =  "AnchorText" },
            new ManagedProperty {  Name =  "AssignedTo" },
            new ManagedProperty {  Name =  "AttachmentDescription" },

            new ManagedProperty {  Name =  "AttachmentType" },
            new ManagedProperty {  Name =  "AttachmentURI" },
            new ManagedProperty {  Name =  "Author" },
            new ManagedProperty {  Name =  "BaseOfficeLocation" },
            new ManagedProperty {  Name =  "BasicScope" },
            new ManagedProperty {  Name =  "body" },
            new ManagedProperty {  Name =  "CategoryNavigationUrl" },
            new ManagedProperty {  Name =  "CCAMetadata" },
            new ManagedProperty {  Name =  "charset" },
            new ManagedProperty {  Name =  "clickdistance" },

            new ManagedProperty {  Name =  "CollapsingStatus" },
            new ManagedProperty {  Name =  "Colleagues" },
            new ManagedProperty {  Name =  "CombinedName" },
            new ManagedProperty {  Name =  "CombinedUserProfileNames" },
            new ManagedProperty {  Name =  "companies" },
            new ManagedProperty {  Name =  "contentclass" },
            new ManagedProperty {  Name =  "ContentModifiedTime" },
            new ManagedProperty {  Name =  "Contents" },
            new ManagedProperty {  Name =  "ContentsHidden" },
            new ManagedProperty {  Name =  "ContentSource" },

            new ManagedProperty {  Name =  "ContentType" },
            new ManagedProperty {  Name =  "ContentTypeId" },
            new ManagedProperty {  Name =  "Created" },
            new ManagedProperty {  Name =  "CreatedBy" },

            new ManagedProperty {  Name =  "Date00" },
            new ManagedProperty {  Name =  "Date01" },
            new ManagedProperty {  Name =  "Date02" },
            new ManagedProperty {  Name =  "Date03" },
            new ManagedProperty {  Name =  "Date04" },
            new ManagedProperty {  Name =  "Date05" },
            new ManagedProperty {  Name =  "Date06" },
            new ManagedProperty {  Name =  "Date07" },
            new ManagedProperty {  Name =  "Date08" },
            new ManagedProperty {  Name =  "Date09" },

            new ManagedProperty {  Name =  "Decimal00" },
            new ManagedProperty {  Name =  "Decimal01" },
            new ManagedProperty {  Name =  "Decimal02" },
            new ManagedProperty {  Name =  "Decimal03" },
            new ManagedProperty {  Name =  "Decimal04" },
            new ManagedProperty {  Name =  "Decimal05" },
            new ManagedProperty {  Name =  "Decimal06" },
            new ManagedProperty {  Name =  "Decimal07" },
            new ManagedProperty {  Name =  "Decimal08" },
            new ManagedProperty {  Name =  "Decimal09" },

            new ManagedProperty {  Name =  "deeplinks" },
            new ManagedProperty {  Name =  "def" },
            new ManagedProperty {  Name =  "defaggre" },
            new ManagedProperty {  Name =  "DefaultEncodingURL" },
            new ManagedProperty {  Name =  "definitioncontent" },
            new ManagedProperty {  Name =  "definitioncontentaggre" },
            new ManagedProperty {  Name =  "Department" },
            new ManagedProperty {  Name =  "Description" },
            new ManagedProperty {  Name =  "DetectedLanguage" },
            new ManagedProperty {  Name =  "DetectedLanguageRanking" },

            new ManagedProperty {  Name =  "DiscoveredTime" },
            new ManagedProperty {  Name =  "DisplayAuthor" },
            new ManagedProperty {  Name =  "DisplayDate" },
            new ManagedProperty {  Name =  "DMSDocAccessRight" },
            new ManagedProperty {  Name =  "DMSDocAuthor" },
            new ManagedProperty {  Name =  "DMSDocTitle" },
            new ManagedProperty {  Name =  "DMSLeaseTerm" },
            new ManagedProperty {  Name =  "docacl" },
            new ManagedProperty {  Name =  "docaclmeta" },
            new ManagedProperty {  Name =  "DocComments" },

            new ManagedProperty {  Name =  "DocId" },
            new ManagedProperty {  Name =  "DocKeywords" },
            new ManagedProperty {  Name =  "docrank" },
            new ManagedProperty {  Name =  "DocSignature" },
            new ManagedProperty {  Name =  "DocSubject" },
            new ManagedProperty {  Name =  "DocumentSignature" },
            new ManagedProperty {  Name =  "DocumentSummary" },
            new ManagedProperty {  Name =  "DocumentSummarySize" },
            new ManagedProperty {  Name =  "docvector" },
            new ManagedProperty {  Name =  "domain" },

            new ManagedProperty {  Name =  "Double00" },
            new ManagedProperty {  Name =  "Double01" },
            new ManagedProperty {  Name =  "Double02" },
            new ManagedProperty {  Name =  "Double03" },
            new ManagedProperty {  Name =  "Double04" },
            new ManagedProperty {  Name =  "Double05" },
            new ManagedProperty {  Name =  "Double06" },
            new ManagedProperty {  Name =  "Double07" },
            new ManagedProperty {  Name =  "Double08" },
            new ManagedProperty {  Name =  "Double09" },

            new ManagedProperty {  Name =  "DuplicateHash" },
            new ManagedProperty {  Name =  "Duplicates" },
            new ManagedProperty {  Name =  "EduAssignmentCategory" },
            new ManagedProperty {  Name =  "EduAssignmentFormat" },
            new ManagedProperty {  Name =  "EduEntityId" },
            new ManagedProperty {  Name =  "EduMaximumScore" },
            new ManagedProperty {  Name =  "EndDate" },
            new ManagedProperty {  Name =  "EventRate" },
            new ManagedProperty {  Name =  "ExcludeFromSummary" },
            new ManagedProperty {  Name =  "ExpirationTime" },

            new ManagedProperty {  Name =  "ExternalMediaURL" },
            new ManagedProperty {  Name =  "ExtractedAuthor" },
            new ManagedProperty {  Name =  "ExtractedDate" },
            new ManagedProperty {  Name =  "fcocount" },
            new ManagedProperty {  Name =  "FileExtension" },
            new ManagedProperty {  Name =  "Filename" },
            new ManagedProperty {  Name =  "FileType" },
            new ManagedProperty {  Name =  "FirstLevelColleagues" },
            new ManagedProperty {  Name =  "FirstLevelMutualFollowings" },
            new ManagedProperty {  Name =  "FirstName" },

            new ManagedProperty {  Name =  "FollowAllAnchor" },
            new ManagedProperty {  Name =  "format" },
            new ManagedProperty {  Name =  "FullPostBody" },
            new ManagedProperty {  Name =  "FullPostTitle" },
            new ManagedProperty {  Name =  "GeneratedTitle" },
            new ManagedProperty {  Name =  "Genre" },
            new ManagedProperty {  Name =  "HierarchyUrl" },
            new ManagedProperty {  Name =  "HitHighlightedProperties" },
            new ManagedProperty {  Name =  "HitHighlightedSummary" },
            new ManagedProperty {  Name =  "HostingPartition" },

            new ManagedProperty {  Name =  "hwboost" },
            new ManagedProperty {  Name =  "ImageDateCreated" },
            new ManagedProperty {  Name =  "importance" },
            
            new ManagedProperty {  Name =  "Int00" },
            new ManagedProperty {  Name =  "Int01" },
            new ManagedProperty {  Name =  "Int02" },
            new ManagedProperty {  Name =  "Int03" },
            new ManagedProperty {  Name =  "Int04" },
            new ManagedProperty {  Name =  "Int05" },
            new ManagedProperty {  Name =  "Int06" },
            new ManagedProperty {  Name =  "Int07" },
            new ManagedProperty {  Name =  "Int08" },
            new ManagedProperty {  Name =  "Int09" },
            new ManagedProperty {  Name =  "Int10" },

            new ManagedProperty {  Name =  "Int11" },
            new ManagedProperty {  Name =  "Int12" },
            new ManagedProperty {  Name =  "Int13" },
            new ManagedProperty {  Name =  "Int14" },
            new ManagedProperty {  Name =  "Int15" },
            new ManagedProperty {  Name =  "Int16" },
            new ManagedProperty {  Name =  "Int17" },
            new ManagedProperty {  Name =  "Int18" },
            new ManagedProperty {  Name =  "Int19" },
            new ManagedProperty {  Name =  "Int20" },

            new ManagedProperty {  Name =  "Int21" },
            new ManagedProperty {  Name =  "Int22" },
            new ManagedProperty {  Name =  "Int23" },
            new ManagedProperty {  Name =  "Int24" },
            new ManagedProperty {  Name =  "Int25" },
            new ManagedProperty {  Name =  "Int26" },
            new ManagedProperty {  Name =  "Int27" },
            new ManagedProperty {  Name =  "Int28" },
            new ManagedProperty {  Name =  "Int29" },
            new ManagedProperty {  Name =  "Int30" },

            new ManagedProperty {  Name =  "Int31" },
            new ManagedProperty {  Name =  "Int32" },
            new ManagedProperty {  Name =  "Int33" },
            new ManagedProperty {  Name =  "Int34" },
            new ManagedProperty {  Name =  "Int35" },
            new ManagedProperty {  Name =  "Int36" },
            new ManagedProperty {  Name =  "Int37" },
            new ManagedProperty {  Name =  "Int38" },
            new ManagedProperty {  Name =  "Int39" },
            new ManagedProperty {  Name =  "Int40" },

            new ManagedProperty {  Name =  "Int41" },
            new ManagedProperty {  Name =  "Int42" },
            new ManagedProperty {  Name =  "Int43" },
            new ManagedProperty {  Name =  "Int44" },
            new ManagedProperty {  Name =  "Int45" },
            new ManagedProperty {  Name =  "Int46" },
            new ManagedProperty {  Name =  "Int47" },
            new ManagedProperty {  Name =  "Int48" },
            new ManagedProperty {  Name =  "Int49" },

            new ManagedProperty {  Name =  "Interests" },
            new ManagedProperty {  Name =  "InternalFileType" },
            new ManagedProperty {  Name =  "IsContainer" },
            new ManagedProperty {  Name =  "IsData" },
            new ManagedProperty {  Name =  "IsDefaultView" },
            new ManagedProperty {  Name =  "IsDocument" },
            new ManagedProperty {  Name =  "IsEmptyList" },
            new ManagedProperty {  Name =  "IsListItem" },
            new ManagedProperty {  Name =  "IsMyDocuments" },
            new ManagedProperty {  Name =  "IsPublishingCatalog" },
            new ManagedProperty {  Name =  "IsReport" },
            new ManagedProperty {  Name =  "ItemCategoryText" },

            new ManagedProperty {  Name =  "JobTitle" },

            new ManagedProperty {  Name =  "Keywords" },

            new ManagedProperty {  Name =  "language" },
            new ManagedProperty {  Name =  "languages" },
            new ManagedProperty {  Name =  "LastAnalyticsUpdateTime" },
            new ManagedProperty {  Name =  "LastModifiedTime" },
            new ManagedProperty {  Name =  "LastName" },
            new ManagedProperty {  Name =  "LevelsToTop" },
            new ManagedProperty {  Name =  "LikesCount" },
            new ManagedProperty {  Name =  "ListID" },
            new ManagedProperty {  Name =  "ListItemID" },
            new ManagedProperty {  Name =  "ListUrl" },
            new ManagedProperty {  Name =  "Location" },

            new ManagedProperty {  Name =  "ManagedProperties" },
            new ManagedProperty {  Name =  "MediaDuration" },
            new ManagedProperty {  Name =  "Memberships" },
            new ManagedProperty {  Name =  "MetadataAuthor" },
            new ManagedProperty {  Name =  "MicroBlogType" },
            new ManagedProperty {  Name =  "MobilePhone" },
            new ManagedProperty {  Name =  "ModifiedBy" },

            new ManagedProperty {  Name =  "NLCodePage" },
            new ManagedProperty {  Name =  "Notes" },
            new ManagedProperty {  Name =  "NumItemsInCollection" },
            
            new ManagedProperty {  Name =  "OfficeNumber" },
            new ManagedProperty {  Name =  "OrgNames" },
            new ManagedProperty {  Name =  "OrgParentNames" },
            new ManagedProperty {  Name =  "OrgParentUrls" },
            new ManagedProperty {  Name =  "OrgUrls" },
            new ManagedProperty {  Name =  "OriginalPath" },
            new ManagedProperty {  Name =  "OWS_ItemURL" },
            new ManagedProperty {  Name =  "OWS_URL" },
            new ManagedProperty {  Name =  "owsmetadatafacetinfo" },
            new ManagedProperty {  Name =  "owstaxidmetadataalltagsinfo" },
            new ManagedProperty {  Name =  "owstaxIdProductCatalogItemCategory" },

            new ManagedProperty {  Name =  "ParentLink" },
            new ManagedProperty {  Name =  "PastProjects" },
            new ManagedProperty {  Name =  "Path" },
            new ManagedProperty {  Name =  "People" },
            new ManagedProperty {  Name =  "PeopleInMedia" },
            new ManagedProperty {  Name =  "PeopleKeywords" },
            new ManagedProperty {  Name =  "PhoneNumber" },
            new ManagedProperty {  Name =  "PictureHeight" },
            new ManagedProperty {  Name =  "PictureThumbnailURL" },
            new ManagedProperty {  Name =  "PictureURL" },
            new ManagedProperty {  Name =  "PictureWidth" },
            new ManagedProperty {  Name =  "PopularSocialTags" },
            new ManagedProperty {  Name =  "PostAuthor" },
            new ManagedProperty {  Name =  "PreferredName" },
            new ManagedProperty {  Name =  "Priority" },
            new ManagedProperty {  Name =  "PrivateColleagues" },
            new ManagedProperty {  Name =  "processingtime" },
            new ManagedProperty {  Name =  "ProductCatalogGroupNumberOWSTEXT" },
            new ManagedProperty {  Name =  "ProfileExpertise" },
            new ManagedProperty {  Name =  "ProfileName" },
            new ManagedProperty {  Name =  "PublishingCatalogSettings" },
            new ManagedProperty {  Name =  "PublishingImage" },
            new ManagedProperty {  Name =  "Pronunciations" },
            new ManagedProperty {  Name =  "Purpose" },
            
            new ManagedProperty {  Name =  "QueryTerms" },

            new ManagedProperty {  Name =  "Rank" },
            new ManagedProperty {  Name =  "RankDetail" },
            new ManagedProperty {  Name =  "RankingWeightHigh" },
            new ManagedProperty {  Name =  "RankingWeightLow" },
            new ManagedProperty {  Name =  "RankingWeightName" },
            new ManagedProperty {  Name =  "Rating" },
            new ManagedProperty {  Name =  "recommendedfor" },
            new ManagedProperty {  Name =  "RecsClickedLifeTime" },
            new ManagedProperty {  Name =  "RecsClickedRecent" },

            new ManagedProperty {  Name =  "RefinableDate00" },
            new ManagedProperty {  Name =  "RefinableDate01" },
            new ManagedProperty {  Name =  "RefinableDate02" },
            new ManagedProperty {  Name =  "RefinableDate03" },
            new ManagedProperty {  Name =  "RefinableDate04" },
            new ManagedProperty {  Name =  "RefinableDate05" },
            new ManagedProperty {  Name =  "RefinableDate06" },
            new ManagedProperty {  Name =  "RefinableDate07" },
            new ManagedProperty {  Name =  "RefinableDate08" },
            new ManagedProperty {  Name =  "RefinableDate08" },
            new ManagedProperty {  Name =  "RefinableDate10" },
            new ManagedProperty {  Name =  "RefinableDate11" },
            new ManagedProperty {  Name =  "RefinableDate12" },
            new ManagedProperty {  Name =  "RefinableDate13" },
            new ManagedProperty {  Name =  "RefinableDate14" },
            new ManagedProperty {  Name =  "RefinableDate15" },
            new ManagedProperty {  Name =  "RefinableDate16" },
            new ManagedProperty {  Name =  "RefinableDate17" },
            new ManagedProperty {  Name =  "RefinableDate18" },
            new ManagedProperty {  Name =  "RefinableDate19" },

            new ManagedProperty {  Name =  "RefinableDecimal00" },
            new ManagedProperty {  Name =  "RefinableDecimal01" },
            new ManagedProperty {  Name =  "RefinableDecimal02" },
            new ManagedProperty {  Name =  "RefinableDecimal03" },
            new ManagedProperty {  Name =  "RefinableDecimal04" },
            new ManagedProperty {  Name =  "RefinableDecimal05" },
            new ManagedProperty {  Name =  "RefinableDecimal06" },
            new ManagedProperty {  Name =  "RefinableDecimal07" },
            new ManagedProperty {  Name =  "RefinableDecimal08" },
            new ManagedProperty {  Name =  "RefinableDecimal09" },

            new ManagedProperty {  Name =  "RefinableDouble00" },
            new ManagedProperty {  Name =  "RefinableDouble01" },
            new ManagedProperty {  Name =  "RefinableDouble02" },
            new ManagedProperty {  Name =  "RefinableDouble03" },
            new ManagedProperty {  Name =  "RefinableDouble04" },
            new ManagedProperty {  Name =  "RefinableDouble05" },
            new ManagedProperty {  Name =  "RefinableDouble06" },
            new ManagedProperty {  Name =  "RefinableDouble07" },
            new ManagedProperty {  Name =  "RefinableDouble08" },
            new ManagedProperty {  Name =  "RefinableDouble09" },

            new ManagedProperty {  Name =  "RefinableInt00" },
            new ManagedProperty {  Name =  "RefinableInt01" },
            new ManagedProperty {  Name =  "RefinableInt02" },
            new ManagedProperty {  Name =  "RefinableInt03" },
            new ManagedProperty {  Name =  "RefinableInt04" },
            new ManagedProperty {  Name =  "RefinableInt05" },
            new ManagedProperty {  Name =  "RefinableInt06" },
            new ManagedProperty {  Name =  "RefinableInt07" },
            new ManagedProperty {  Name =  "RefinableInt08" },
            new ManagedProperty {  Name =  "RefinableInt09" },

            new ManagedProperty {  Name =  "RefinableInt10" },
            new ManagedProperty {  Name =  "RefinableInt11" },
            new ManagedProperty {  Name =  "RefinableInt12" },
            new ManagedProperty {  Name =  "RefinableInt13" },
            new ManagedProperty {  Name =  "RefinableInt14" },
            new ManagedProperty {  Name =  "RefinableInt15" },
            new ManagedProperty {  Name =  "RefinableInt16" },
            new ManagedProperty {  Name =  "RefinableInt17" },
            new ManagedProperty {  Name =  "RefinableInt18" },
            new ManagedProperty {  Name =  "RefinableInt19" },

            new ManagedProperty {  Name =  "RefinableInt20" },
            new ManagedProperty {  Name =  "RefinableInt21" },
            new ManagedProperty {  Name =  "RefinableInt22" },
            new ManagedProperty {  Name =  "RefinableInt23" },
            new ManagedProperty {  Name =  "RefinableInt24" },
            new ManagedProperty {  Name =  "RefinableInt25" },
            new ManagedProperty {  Name =  "RefinableInt26" },
            new ManagedProperty {  Name =  "RefinableInt27" },
            new ManagedProperty {  Name =  "RefinableInt28" },
            new ManagedProperty {  Name =  "RefinableInt29" },

            new ManagedProperty {  Name =  "RefinableInt30" },
            new ManagedProperty {  Name =  "RefinableInt31" },
            new ManagedProperty {  Name =  "RefinableInt32" },
            new ManagedProperty {  Name =  "RefinableInt33" },
            new ManagedProperty {  Name =  "RefinableInt34" },
            new ManagedProperty {  Name =  "RefinableInt35" },
            new ManagedProperty {  Name =  "RefinableInt36" },
            new ManagedProperty {  Name =  "RefinableInt37" },
            new ManagedProperty {  Name =  "RefinableInt38" },
            new ManagedProperty {  Name =  "RefinableInt39" },

            new ManagedProperty {  Name =  "RefinableInt40" },
            new ManagedProperty {  Name =  "RefinableInt41" },
            new ManagedProperty {  Name =  "RefinableInt42" },
            new ManagedProperty {  Name =  "RefinableInt43" },
            new ManagedProperty {  Name =  "RefinableInt44" },
            new ManagedProperty {  Name =  "RefinableInt45" },
            new ManagedProperty {  Name =  "RefinableInt46" },
            new ManagedProperty {  Name =  "RefinableInt47" },
            new ManagedProperty {  Name =  "RefinableInt48" },
            new ManagedProperty {  Name =  "RefinableInt49" },

            new ManagedProperty {  Name =  "RefinableString00" },
            new ManagedProperty {  Name =  "RefinableString01" },
            new ManagedProperty {  Name =  "RefinableString02" },
            new ManagedProperty {  Name =  "RefinableString03" },
            new ManagedProperty {  Name =  "RefinableString04" },
            new ManagedProperty {  Name =  "RefinableString05" },
            new ManagedProperty {  Name =  "RefinableString06" },
            new ManagedProperty {  Name =  "RefinableString07" },
            new ManagedProperty {  Name =  "RefinableString08" },
            new ManagedProperty {  Name =  "RefinableString09" },

            new ManagedProperty {  Name =  "RefinableString10" },
            new ManagedProperty {  Name =  "RefinableString11" },
            new ManagedProperty {  Name =  "RefinableString12" },
            new ManagedProperty {  Name =  "RefinableString13" },
            new ManagedProperty {  Name =  "RefinableString14" },
            new ManagedProperty {  Name =  "RefinableString15" },
            new ManagedProperty {  Name =  "RefinableString16" },
            new ManagedProperty {  Name =  "RefinableString17" },
            new ManagedProperty {  Name =  "RefinableString18" },
            new ManagedProperty {  Name =  "RefinableString19" },

            new ManagedProperty {  Name =  "RefinableString20" },
            new ManagedProperty {  Name =  "RefinableString21" },
            new ManagedProperty {  Name =  "RefinableString22" },
            new ManagedProperty {  Name =  "RefinableString23" },
            new ManagedProperty {  Name =  "RefinableString24" },
            new ManagedProperty {  Name =  "RefinableString25" },
            new ManagedProperty {  Name =  "RefinableString26" },
            new ManagedProperty {  Name =  "RefinableString27" },
            new ManagedProperty {  Name =  "RefinableString28" },
            new ManagedProperty {  Name =  "RefinableString29" },

            new ManagedProperty {  Name =  "RefinableString30" },
            new ManagedProperty {  Name =  "RefinableString31" },
            new ManagedProperty {  Name =  "RefinableString32" },
            new ManagedProperty {  Name =  "RefinableString33" },
            new ManagedProperty {  Name =  "RefinableString34" },
            new ManagedProperty {  Name =  "RefinableString35" },
            new ManagedProperty {  Name =  "RefinableString36" },
            new ManagedProperty {  Name =  "RefinableString37" },
            new ManagedProperty {  Name =  "RefinableString38" },
            new ManagedProperty {  Name =  "RefinableString39" },

            new ManagedProperty {  Name =  "RefinableString40" },
            new ManagedProperty {  Name =  "RefinableString41" },
            new ManagedProperty {  Name =  "RefinableString42" },
            new ManagedProperty {  Name =  "RefinableString43" },
            new ManagedProperty {  Name =  "RefinableString44" },
            new ManagedProperty {  Name =  "RefinableString45" },
            new ManagedProperty {  Name =  "RefinableString46" },
            new ManagedProperty {  Name =  "RefinableString47" },
            new ManagedProperty {  Name =  "RefinableString48" },
            new ManagedProperty {  Name =  "RefinableString49" },

            new ManagedProperty {  Name =  "RefinableString50" },
            new ManagedProperty {  Name =  "RefinableString51" },
            new ManagedProperty {  Name =  "RefinableString52" },
            new ManagedProperty {  Name =  "RefinableString53" },
            new ManagedProperty {  Name =  "RefinableString54" },
            new ManagedProperty {  Name =  "RefinableString55" },
            new ManagedProperty {  Name =  "RefinableString56" },
            new ManagedProperty {  Name =  "RefinableString57" },
            new ManagedProperty {  Name =  "RefinableString58" },
            new ManagedProperty {  Name =  "RefinableString59" },

            new ManagedProperty {  Name =  "RefinableString60" },
            new ManagedProperty {  Name =  "RefinableString61" },
            new ManagedProperty {  Name =  "RefinableString62" },
            new ManagedProperty {  Name =  "RefinableString63" },
            new ManagedProperty {  Name =  "RefinableString64" },
            new ManagedProperty {  Name =  "RefinableString65" },
            new ManagedProperty {  Name =  "RefinableString66" },
            new ManagedProperty {  Name =  "RefinableString67" },
            new ManagedProperty {  Name =  "RefinableString68" },
            new ManagedProperty {  Name =  "RefinableString69" },

            new ManagedProperty {  Name =  "RefinableString70" },
            new ManagedProperty {  Name =  "RefinableString71" },
            new ManagedProperty {  Name =  "RefinableString72" },
            new ManagedProperty {  Name =  "RefinableString73" },
            new ManagedProperty {  Name =  "RefinableString74" },
            new ManagedProperty {  Name =  "RefinableString75" },
            new ManagedProperty {  Name =  "RefinableString76" },
            new ManagedProperty {  Name =  "RefinableString77" },
            new ManagedProperty {  Name =  "RefinableString78" },
            new ManagedProperty {  Name =  "RefinableString79" },

            new ManagedProperty {  Name =  "RefinableString80" },
            new ManagedProperty {  Name =  "RefinableString81" },
            new ManagedProperty {  Name =  "RefinableString82" },
            new ManagedProperty {  Name =  "RefinableString83" },
            new ManagedProperty {  Name =  "RefinableString84" },
            new ManagedProperty {  Name =  "RefinableString85" },
            new ManagedProperty {  Name =  "RefinableString86" },
            new ManagedProperty {  Name =  "RefinableString87" },
            new ManagedProperty {  Name =  "RefinableString88" },
            new ManagedProperty {  Name =  "RefinableString89" },

            new ManagedProperty {  Name =  "RefinableString90" },
            new ManagedProperty {  Name =  "RefinableString91" },
            new ManagedProperty {  Name =  "RefinableString92" },
            new ManagedProperty {  Name =  "RefinableString93" },
            new ManagedProperty {  Name =  "RefinableString94" },
            new ManagedProperty {  Name =  "RefinableString95" },
            new ManagedProperty {  Name =  "RefinableString96" },
            new ManagedProperty {  Name =  "RefinableString97" },
            new ManagedProperty {  Name =  "RefinableString98" },
            new ManagedProperty {  Name =  "RefinableString99" },

            new ManagedProperty {  Name =  "ReplyCount" },
            new ManagedProperty {  Name =  "Responsibilities" },
            new ManagedProperty {  Name =  "RobotsNoIndex" },
            new ManagedProperty {  Name =  "RootPostID" },
            new ManagedProperty {  Name =  "RootPostOwnerID" },
            new ManagedProperty {  Name =  "RootPostUniqueID" },

            new ManagedProperty {  Name =  "Schools" },
            new ManagedProperty {  Name =  "SecondaryFileExtension" },
            new ManagedProperty {  Name =  "SecondLevelColleagues" },
            new ManagedProperty {  Name =  "SectionIndexes" },
            new ManagedProperty {  Name =  "SectionNames" },
            new ManagedProperty {  Name =  "SecondLevelColleagues" },
            new ManagedProperty {  Name =  "ServerRedirectedEmbedURL" },
            new ManagedProperty {  Name =  "ServerRedirectedPreviewURL" },
            new ManagedProperty {  Name =  "ServerRedirectedURL" },
            new ManagedProperty {  Name =  "ServiceApplicationID" },
            new ManagedProperty {  Name =  "SharedWithInternal" },
            new ManagedProperty {  Name =  "SipAddress" },
            new ManagedProperty {  Name =  "Site" },
            new ManagedProperty {  Name =  "SiteClosed" },
            new ManagedProperty {  Name =  "SiteDescription" },
            new ManagedProperty {  Name =  "SiteID" },
            new ManagedProperty {  Name =  "SiteLogo" },
            new ManagedProperty {  Name =  "SitemapChangeFrequency" },
            new ManagedProperty {  Name =  "SitemapPriority" },
            new ManagedProperty {  Name =  "SiteMembers" },
            new ManagedProperty {  Name =  "sitename" },
            new ManagedProperty {  Name =  "SiteOwners" },
            new ManagedProperty {  Name =  "siterank" },
            new ManagedProperty {  Name =  "SiteTitle" },
            new ManagedProperty {  Name =  "Size" },
            new ManagedProperty {  Name =  "Skills" },
            new ManagedProperty {  Name =  "SocialTag" },
            new ManagedProperty {  Name =  "SocialTagTextUrl" },
            new ManagedProperty {  Name =  "SPContentType" },
            new ManagedProperty {  Name =  "SpellingTerms" },
            new ManagedProperty {  Name =  "SPSiteURL" },
            new ManagedProperty {  Name =  "SPVersion" },
            new ManagedProperty {  Name =  "StartDate" },
            new ManagedProperty {  Name =  "Status" },

            new ManagedProperty {  Name =  "Tags" },
            new ManagedProperty {  Name =  "teaser" },
            new ManagedProperty {  Name =  "Text1" },
            new ManagedProperty {  Name =  "Text2" },
            new ManagedProperty {  Name =  "Text3" },
            new ManagedProperty {  Name =  "Title" },
            new ManagedProperty {  Name =  "tld" },

            new ManagedProperty {  Name =  "UniqueID" },
            new ManagedProperty {  Name =  "url" },
            new ManagedProperty {  Name =  "UrlDepth" },
            new ManagedProperty {  Name =  "urlkeywords" },
            new ManagedProperty {  Name =  "urls" },
            new ManagedProperty {  Name =  "UsageAnalyticsId" },

            new ManagedProperty {  Name =  "UsageEvent10LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent10Recent" },
            
            new ManagedProperty {  Name =  "UsageEvent11LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent11Recent" },

            new ManagedProperty {  Name =  "UsageEvent12LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent12Recent" },

            new ManagedProperty {  Name =  "UsageEvent1LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent1Recent" },

            new ManagedProperty {  Name =  "UsageEvent2LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent2Recent" },

            new ManagedProperty {  Name =  "UsageEvent3LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent3Recent" },

            new ManagedProperty {  Name =  "UsageEvent4LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent4Recent" },

            new ManagedProperty {  Name =  "UsageEvent5LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent5Recent" },

            new ManagedProperty {  Name =  "UsageEvent6LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent6Recent" },

            new ManagedProperty {  Name =  "UsageEvent7LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent7Recent" },

            new ManagedProperty {  Name =  "UsageEvent8LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent8Recent" },

            new ManagedProperty {  Name =  "UsageEvent9LifeTime" },
            new ManagedProperty {  Name =  "UsageEvent9Recent" },

            new ManagedProperty {  Name =  "UsageEventItemId" },
            new ManagedProperty {  Name =  "UserEncodingURL" },
            new ManagedProperty {  Name =  "UserName" },
            new ManagedProperty {  Name =  "UserProfile_GUID" },

            new ManagedProperty {  Name =  "ViewsLast1Days" },
            new ManagedProperty {  Name =  "ViewsLast1DaysUniqueUsers" },

            new ManagedProperty {  Name =  "ViewsLast2Days" },
            new ManagedProperty {  Name =  "ViewsLast2DaysUniqueUsers" },

            new ManagedProperty {  Name =  "ViewsLast3Days" },
            new ManagedProperty {  Name =  "ViewsLast3DaysUniqueUsers" },

            new ManagedProperty {  Name =  "ViewsLast4Days" },
            new ManagedProperty {  Name =  "ViewsLast4DaysUniqueUsers" },

            new ManagedProperty {  Name =  "ViewsLast5Days" },
            new ManagedProperty {  Name =  "ViewsLast5DaysUniqueUsers" },

            new ManagedProperty {  Name =  "ViewsLast6Days" },
            new ManagedProperty {  Name =  "ViewsLast6DaysUniqueUsers" },

            new ManagedProperty {  Name =  "ViewsLast7Days" },
            new ManagedProperty {  Name =  "ViewsLast7DaysUniqueUsers" },

            new ManagedProperty {  Name =  "ViewsLastMonths1" },
            new ManagedProperty {  Name =  "ViewsLastMonths1Unique" },

            new ManagedProperty {  Name =  "ViewsLastMonths2" },
            new ManagedProperty {  Name =  "ViewsLastMonths2Unique" },

            new ManagedProperty {  Name =  "ViewsLastMonths3" },
            new ManagedProperty {  Name =  "ViewsLastMonths3Unique" },

            new ManagedProperty {  Name =  "ViewsLifeTime" },
            new ManagedProperty {  Name =  "ViewsLifeTimeUniqueUsers" },
            new ManagedProperty {  Name =  "ViewsRecent" },
            new ManagedProperty {  Name =  "ViewsRecentUniqueUsers" },
            
            new ManagedProperty {  Name =  "WebId" },
            new ManagedProperty {  Name =  "WebTemplate" },
            new ManagedProperty {  Name =  "WeightedMemberships" },
            new ManagedProperty {  Name =  "WikiCategory" },
            
            new ManagedProperty {  Name =  "WordCustomRefiner1" },
            new ManagedProperty {  Name =  "WordCustomRefiner2" },
            new ManagedProperty {  Name =  "WordCustomRefiner3" },
            new ManagedProperty {  Name =  "WordCustomRefiner4" },
            new ManagedProperty {  Name =  "WordCustomRefiner5" },

            new ManagedProperty {  Name =  "WordExactCustomRefiner" },

            new ManagedProperty {  Name =  "WordPartCustomRefiner1" },
            new ManagedProperty {  Name =  "WordPartCustomRefiner2" },
            new ManagedProperty {  Name =  "WordPartCustomRefiner3" },
            new ManagedProperty {  Name =  "WordPartCustomRefiner4" },
            new ManagedProperty {  Name =  "WordPartCustomRefiner5" },

            new ManagedProperty {  Name =  "WordPartExactCustomRefiner" },
            
            new ManagedProperty {  Name =  "WorkEmail" },
            new ManagedProperty {  Name =  "WorkId" },
            new ManagedProperty {  Name =  "WorkPhone" },
            new ManagedProperty {  Name =  "YomiDisplayName" },
        };

        #endregion

    }
}
